-- VectariaCodes STEP 6 database schema
-- Run this entire file in the Supabase SQL Editor.
-- Afterward enable Anonymous Sign-Ins in Supabase Authentication settings.
-- STEP 7 will add permanent account providers and administrator roles.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Creator',
  handle text not null default 'creator',
  bio text not null default 'Creator profile for VectariaCodes.',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_handle_lower_idx
  on public.profiles (lower(handle));

create table if not exists public.projects (
  id text primary key default gen_random_uuid()::text,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text not null check (category in ('CSS Themes','UserScripts','Game Mods')),
  description text not null,
  tags text[] not null default '{}',
  file_name text not null,
  code text not null,
  likes_count integer not null default 0 check (likes_count >= 0),
  views_count integer not null default 0 check (views_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists projects_owner_name_lower_idx
  on public.projects (owner_id, lower(name));

create index if not exists projects_created_at_idx
  on public.projects (created_at desc);

create index if not exists projects_category_idx
  on public.projects (category);

create table if not exists public.project_likes (
  project_id text not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (project_id, user_id)
);

create table if not exists public.activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  project_id text references public.projects(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.project_likes enable row level security;
alter table public.activity enable row level security;

-- Public project/profile reading.
drop policy if exists "Public can read profiles" on public.profiles;
create policy "Public can read profiles"
  on public.profiles for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can read projects" on public.projects;
create policy "Public can read projects"
  on public.projects for select
  to anon, authenticated
  using (true);

-- Each signed-in/anonymous-authenticated user owns their profile.
drop policy if exists "Users can create own profile" on public.profiles;
create policy "Users can create own profile"
  on public.profiles for insert
  to authenticated
  with check ((select auth.uid()) = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

-- Project ownership policies.
drop policy if exists "Users can create own projects" on public.projects;
create policy "Users can create own projects"
  on public.projects for insert
  to authenticated
  with check ((select auth.uid()) = owner_id);

drop policy if exists "Users can update own projects" on public.projects;
create policy "Users can update own projects"
  on public.projects for update
  to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

drop policy if exists "Users can delete own projects" on public.projects;
create policy "Users can delete own projects"
  on public.projects for delete
  to authenticated
  using ((select auth.uid()) = owner_id);

-- Likes are tied to the current authenticated user.
drop policy if exists "Users can read own likes" on public.project_likes;
create policy "Users can read own likes"
  on public.project_likes for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can create own likes" on public.project_likes;
create policy "Users can create own likes"
  on public.project_likes for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own likes" on public.project_likes;
create policy "Users can delete own likes"
  on public.project_likes for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- Activity is private to the current user for now.
drop policy if exists "Users can read own activity" on public.activity;
create policy "Users can read own activity"
  on public.activity for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can create own activity" on public.activity;
create policy "Users can create own activity"
  on public.activity for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

-- Secure counters behind database functions so the browser never needs an elevated key.
create or replace function public.increment_project_view(p_project_id text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.projects
  set views_count = views_count + 1,
      updated_at = now()
  where id = p_project_id;
$$;

grant execute on function public.increment_project_view(text) to anon, authenticated;

create or replace function public.toggle_project_like(p_project_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  now_liked boolean;
begin
  if uid is null then
    raise exception 'Authentication required';
  end if;

  if exists (
    select 1 from public.project_likes
    where project_id = p_project_id and user_id = uid
  ) then
    delete from public.project_likes
    where project_id = p_project_id and user_id = uid;
    update public.projects
    set likes_count = greatest(likes_count - 1, 0), updated_at = now()
    where id = p_project_id;
    now_liked := false;
  else
    insert into public.project_likes(project_id, user_id)
    values (p_project_id, uid);
    update public.projects
    set likes_count = likes_count + 1, updated_at = now()
    where id = p_project_id;
    now_liked := true;
  end if;

  return now_liked;
end;
$$;

grant execute on function public.toggle_project_like(text) to authenticated;

-- Keep counters consistent if a project is deleted by cascading its likes.
-- Optional cleanup helper for anonymous users; run manually when needed.
-- delete from auth.users
-- where is_anonymous = true and created_at < now() - interval '30 days';


-- STEP 7 authentication additions
-- Email/password and OAuth providers are configured in Supabase Dashboard.
-- Do not put provider client secrets in this repository.

alter table public.profiles add column if not exists role text not null default 'user' check (role in ('user','admin'));

create or replace function public.prevent_profile_role_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.role is distinct from old.role and old.role <> 'admin' then
    new.role := old.role;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_protect_role on public.profiles;
create trigger profiles_protect_role
before update on public.profiles
for each row execute function public.prevent_profile_role_change();

-- To grant the site owner/admin role, run this manually for the verified account UUID:
-- update public.profiles set role = 'admin' where id = 'YOUR-USER-UUID';

-- Optional: keep anonymous users from publishing once STEP 7 auth is enabled.
drop policy if exists "Permanent users can create own projects" on public.projects;
create policy "Permanent users can create own projects"
  on public.projects for insert
  to authenticated
  with check ((select auth.uid()) = owner_id and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) is false);

drop policy if exists "Permanent users can update own projects" on public.projects;
create policy "Permanent users can update own projects"
  on public.projects for update
  to authenticated
  using ((select auth.uid()) = owner_id and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) is false)
  with check ((select auth.uid()) = owner_id and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) is false);

drop policy if exists "Permanent users can delete own projects" on public.projects;
create policy "Permanent users can delete own projects"
  on public.projects for delete
  to authenticated
  using ((select auth.uid()) = owner_id and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) is false);
